### ISSUE TITLE
What GPS type in your demo?

### ISSUE THREAD

**Issue by Dreamzz5** [zhuang-hao-ming/map-match#5]
**What GPS type in your demo?**

I want to use map-matching in this repository and in formal, the GPS will not larger than 200.  But in your data, the latitude and longitude are too much bigger.  So I want to know how to get the data type as the same as you.

![image](https://user-images.githubusercontent.com/46215105/104736090-5aeaf780-573a-11eb-9d99-7cd39936ee70.png)

**Comment by zhuang-hao-ming** [comment]
The sample data uses a projected coordinate system (EPSG: 32649). To be able to calculate, you need to project the road network and GPS onto the same projected coordinate system.
